/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Platform } from "./Platform";
export * as factories from "./factories";
export { Platform__factory } from "./factories/Platform__factory";
